# Generated by Django 2.2.5 on 2020-07-11 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnlocksApp', '0002_auto_20200703_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='category',
            field=models.CharField(choices=[('Nord', 'Nord VPN'), ('DSTV', 'DSTV'), ('CourseHero', 'CourseHero Logins'), ('Netflix Logins', 'Netflix Logins'), ('Grammarly', 'Grammarly Premium'), ('Chegg', 'Chegg Logins'), ('Scrbd', 'Scrbd Logins'), ('Turnitin', 'Turnitin Logins')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logins',
            name='other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unlocks',
            name='category',
            field=models.CharField(choices=[('Chegg', 'Chegg Unlocks'), ('Scrbd', 'Scrbd Unlocks'), ('CourseHero', 'CourseHero Unlocks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unlocks',
            name='other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='unlocks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
