# Generated by Django 2.2.5 on 2020-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnlocksApp', '0003_auto_20200711_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='category',
            field=models.CharField(choices=[('DSTV', 'DSTV'), ('Grammarly', 'Grammarly Premium'), ('Nord', 'Nord VPN'), ('CourseHero', 'CourseHero Logins'), ('Chegg', 'Chegg Logins'), ('Scrbd', 'Scrbd Logins'), ('Netflix Logins', 'Netflix Logins'), ('Turnitin', 'Turnitin Logins')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unlocks',
            name='category',
            field=models.CharField(choices=[('CourseHero', 'CourseHero Unlocks'), ('Scrbd', 'Scrbd Unlocks'), ('Chegg', 'Chegg Unlocks')], max_length=20),
        ),
    ]
