# Generated by Django 2.2.5 on 2020-07-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnlocksApp', '0004_auto_20200718_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='req_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unlocks',
            name='req_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logins',
            name='category',
            field=models.CharField(choices=[('Nord', 'Nord VPN'), ('DSTV', 'DSTV'), ('Turnitin', 'Turnitin Logins'), ('Chegg', 'Chegg Logins'), ('Scrbd', 'Scrbd Logins'), ('Grammarly', 'Grammarly Premium'), ('Netflix Logins', 'Netflix Logins'), ('CourseHero', 'CourseHero Logins')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unlocks',
            name='category',
            field=models.CharField(choices=[('Chegg', 'Chegg Unlocks'), ('CourseHero', 'CourseHero Unlocks'), ('Scrbd', 'Scrbd Unlocks')], max_length=20),
        ),
    ]
