# Generated by Django 2.2.5 on 2020-07-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnlocksApp', '0005_auto_20200720_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='category',
            field=models.CharField(choices=[('Grammarly', 'Grammarly Premium'), ('CourseHero', 'CourseHero Logins'), ('Netflix Logins', 'Netflix Logins'), ('Turnitin', 'Turnitin Logins'), ('DSTV', 'DSTV'), ('Chegg', 'Chegg Logins'), ('Scrbd', 'Scrbd Logins'), ('Nord', 'Nord VPN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unlocks',
            name='category',
            field=models.CharField(choices=[('CourseHero', 'CourseHero Unlocks'), ('Scrbd', 'Scrbd Unlocks'), ('Chegg', 'Chegg Unlocks')], max_length=20),
        ),
    ]
