# Generated by Django 2.2.5 on 2020-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnlocksApp', '0006_auto_20200720_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logins_passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='logins',
            name='category',
            field=models.CharField(choices=[('Nord', 'Nord VPN'), ('Grammarly', 'Grammarly Premium'), ('DSTV', 'DSTV'), ('Chegg', 'Chegg Logins'), ('Scrbd', 'Scrbd Logins'), ('Turnitin', 'Turnitin Logins'), ('Netflix', 'Netflix Logins'), ('CourseHero', 'CourseHero Logins')], max_length=20),
        ),
    ]
