# Generated by Django 2.2.5 on 2020-01-27 13:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200127_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawpayouts',
            name='last_name',
            field=models.CharField(default='misiko', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawpayouts',
            name='payment_mode',
            field=models.CharField(choices=[('p', 'Paypal'), ('M', 'Mpesa')], default='Mpesa', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawpayouts',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
    ]
