# Generated by Django 2.2.5 on 2020-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200127_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawpayouts',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='withdrawpayouts',
            name='payment_mode',
            field=models.CharField(choices=[('M', 'Mpesa'), ('p', 'Paypal')], max_length=20),
        ),
    ]
