# Generated by Django 2.2.5 on 2020-01-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200127_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawpayouts',
            options={'get_latest_by': ['-date']},
        ),
    ]
