# Generated by Django 2.2.5 on 2020-04-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='order',
            new_name='orderid',
        ),
        migrations.AddField(
            model_name='refund',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawpayouts',
            name='payment_mode',
            field=models.CharField(choices=[('p', 'Paypal'), ('M', 'Mpesa')], max_length=20),
        ),
    ]
