# Generated by Django 2.2.5 on 2020-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200407_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
