# Generated by Django 2.2.5 on 2020-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20200616_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawpayouts',
            old_name='amount',
            new_name='amount_dispensed',
        ),
        migrations.AddField(
            model_name='withdrawpayouts',
            name='amount_requested',
            field=models.FloatField(default=0.0),
        ),
    ]
