# Generated by Django 2.2.5 on 2020-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200625_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_notifications',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='email_notifications',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawpayouts',
            name='payment_mode',
            field=models.CharField(choices=[('M', 'Mpesa'), ('p', 'Paypal')], max_length=20),
        ),
    ]
