# Generated by Django 2.2.5 on 2020-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C2bTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=50, null=True)),
                ('TransID', models.CharField(blank=True, max_length=50, null=True)),
                ('TransTime', models.DateTimeField(blank=True, null=True)),
                ('TransAmount', models.CharField(blank=True, max_length=50, null=True)),
                ('BusinessShortCode', models.CharField(blank=True, max_length=50, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=50, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=50, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=50, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('ResultCode', models.IntegerField(blank=True, null=True)),
                ('ResultDesc', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance', models.CharField(default=0, max_length=12)),
                ('TranscationDate', models.DateTimeField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
