# Generated by Django 2.2.5 on 2020-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MpesaApp', '0002_b2ctransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNMOnline2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('ResultCode', models.IntegerField(blank=True, null=True)),
                ('ResultDesc', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance', models.CharField(default=0, max_length=12)),
                ('TranscationDate', models.DateTimeField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
