# Generated by Django 2.2.5 on 2020-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200327_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Ivy', 'Ivy'), ('Juniour', 'Junior'), ('r', 'Seni0r'), ('Intermediate', 'Intermediate')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Transcribing Account'), ('sw', 'Take Account'), ('s', 'Bidding Account')], max_length=2),
        ),
    ]
