# Generated by Django 2.2.5 on 2019-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20191002_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], max_length=1),
        ),
    ]
