# Generated by Django 2.2.5 on 2020-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200327_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Juniour', 'Junior'), ('Intermediate', 'Intermediate'), ('Ivy', 'Ivy'), ('r', 'Seni0r')], max_length=15, null=True),
        ),
    ]
