# Generated by Django 2.2.5 on 2019-10-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20191002_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Label',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Transcribing Account'), ('sw', 'Take Account'), ('s', 'Bidding Account')], max_length=2),
        ),
    ]
