# Generated by Django 2.2.5 on 2020-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200618_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Intermediate', 'Intermediate'), ('Juniour', 'Junior'), ('r', 'Seni0r'), ('Ivy', 'Ivy')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Transcribing Account'), ('s', 'Bidding Account'), ('sw', 'Take Account')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('P', 'primary'), ('S', 'secondary')], max_length=1),
        ),
    ]
