# Generated by Django 2.2.5 on 2020-07-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200718_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Senior', 'Senior'), ('Juniour', 'Junior'), ('Ivy', 'Ivy'), ('Intermediate', 'Intermediate')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('s', 'Bidding Account'), ('sw', 'Take Account'), ('OW', 'Transcribing Account')], max_length=2),
        ),
    ]
