# Generated by Django 2.2.5 on 2020-06-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20200529_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Juniour', 'Junior'), ('Intermediate', 'Intermediate'), ('r', 'Seni0r'), ('Ivy', 'Ivy')], max_length=15, null=True),
        ),
    ]
