# Generated by Django 2.2.5 on 2019-11-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_auto_20191109_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], max_length=1),
        ),
    ]
