# Generated by Django 2.2.5 on 2019-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_auto_20191109_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('sw', 'Take Account'), ('s', 'Bidding Account'), ('OW', 'Transcribing Account')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
