# Generated by Django 2.2.5 on 2019-11-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0037_auto_20191110_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Intermediate', 'Intermediate'), ('Juniour', 'Junior'), ('Ivy', 'Ivy'), ('r', 'Seni0r')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Reviews',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='finished_orders',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('sw', 'Take Account'), ('OW', 'Transcribing Account'), ('s', 'Bidding Account')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('D', 'danger'), ('P', 'primary')], max_length=1),
        ),
    ]
