# Generated by Django 2.2.5 on 2019-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0041_auto_20191114_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnmonline',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='Level',
            field=models.CharField(blank=True, choices=[('Ivy', 'Ivy'), ('Intermediate', 'Intermediate'), ('Juniour', 'Junior'), ('r', 'Seni0r')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], max_length=1),
        ),
    ]
