# Generated by Django 2.2.5 on 2020-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paypal_callbacktb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultid', models.CharField(blank=True, max_length=50, null=True)),
                ('payout_batch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_status', models.CharField(blank=True, max_length=20, null=True)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('sender_batch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('fees', models.FloatField(default=0.0)),
                ('payments', models.IntegerField(default=0)),
            ],
        ),
    ]
